-- NOP
resource.AddFile("materials/one_hud/health.png"),
resource.AddFile("materials/one_hud/shield.png"),
resource.AddFile("materials/one_hud/team.png"),
resource.AddFile("materials/one_hud/wallet.png"),
resource.AddFile("materials/one_hud/food.png"),
resource.AddFile("materials/one_hud/ammo.png"),
resource.AddFile("materials/one_hud/ping.png"),
resource.AddFile("materials/one_hud/level.png"),
resource.AddFile("materials/one_hud/name.png"),
resource.AddFile("materials/one_hud/rank.png"),
resource.AddFile("materials/one_hud/group.png"),
resource.AddFile("materials/one_hud/props.png"),
resource.AddFile("materials/one_hud/ammo.png"),
resource.AddFile("materials/one_hud/spe_ammo.png"),
resource.AddFile("materials/one_hud/weapon.png"),
resource.AddFile("materials/one_hud/talk.png"),